### ISSUE TITLE
APP_ROUTES

### ISSUE THREAD

**Issue by Mtix** [aiprogs/angular-rxjs#1]
https://github.com/aiprogs/angular-rxjs/blob/4872e74241c6c1829f9a5a49f71a03a6cd500a5e/src/app/app-routing.module.ts#L4

Предлагаю константы роутов экспортить из модуля которому они пренадлежат, общий файл разрастётся и невозможно будет поддерживать + при удалении модуля с роутингом общие констансы останутся и где-то в приложении будут вести на 404

**Comment by aiprogs** [comment]
@Mtix согласен. Убрал
