### ISSUE TITLE
Абстрактный класс

### ISSUE THREAD

**Issue by Mtix** [aiprogs/angular-rxjs#2]
https://github.com/aiprogs/angular-rxjs/blob/d68fa6c4c70b1682d5dbab38a850d1fcbbd60980/src/app/core/services/base-service.class.ts#L6

Здесь получается не абстрактный класс, абстрактый класс не может содержать реализации

**Comment by aiprogs** [comment]
@Mtix использование abstract класса обусловлено желанием навязать контракт другим core сервисам.

**Comment by aiprogs** [comment]
Абстрактный класс может содержать общие реализации.
